services:
  runner:
    build:
      context: .
    image: dkr.gtl.net/dkr/devops-tools-container-image-job-runner
    volumes:
    - .:/var/workspace:rw
    working_dir: /var/workspace
  kaniko:
    image: gcr.io/kaniko-project/executor:debug
    volumes:
    - .:/var/workspace:rw
    working_dir: /var/workspace
    entrypoint: sh
